apiVersion : apps/v1
kind: Deployment
metadata:
  name: paymentapi-deployment
spec:
  selector:
    matchLabels:
      app: paymentapi-pod
  template:
    metadata:
      labels:
        app: paymentapi-pod
    spec:
      containers:
        - name: paymentapi-container
          image: paymentapiservice.azurecr.io/paymentmicroservice:new
          resource: 
            limits: 
                memory: "128Mi"
                cpu: "500m"
            ports:
            - containerPort: 80